### ISSUE TITLE
Support for version 1.25.1

### ISSUE THREAD

**Issue by AByakugans** [bsq-ports/Chroma#34]
Hello,
There is missing support for the newest version of the game 1.25.1 - just letting you know in case someone missed it.
Thank you!

**Comment by AKASGaming** [comment]
Bruh, it only came out less than a week ago, give them time

**Comment by BoogieHasFun** [comment]
give him some time damn, he is probably working on support 1.25.1 just wait

**Comment by AByakugans** [comment]
In case you missed my message I wrote " just letting you know in case someone missed it." it is a valid thing I guess I am not blaming anyone for not updating just reporting an issue so calm down, please.

**Comment by AKASGaming** [comment]
Do you seriously think they wouldn't know already? Especially with people like you that spam devs about new updates

**Comment by AByakugans** [comment]
Where do you see me spamming? And how do you know what devs know? I just created one issue which is valid. Go back to you cave please and stop spamming my issue with nonsense, thank you!

**Comment by BoogieHasFun** [comment]
use the issues section for real issues. and the mod not being updated for the current version of the game the game is not an issue, rather a annoyance for the developer working on the mod.

**Comment by AByakugans** [comment]
Let developer decide that, please, and finally stop spamming this issue!
Thank you!

**Comment by AKASGaming** [comment]
Sine your brain is too dense to understand what's happening, let me put it like this for you, how would you like it if you publicly made a mistake and now hundreds of people are here to let you know? That's pretty much what happens when beat saber updates and hundreds of people complain that the mod doesn't work anymore. The dev most likely knew it needed an update already and didn't need the hundred other people letting them know
